<?php
declare(strict_types=1);

namespace KayStrobach\Migrations\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MigrateCommand extends \Doctrine\Migrations\Tools\Console\Command\MigrateCommand
{

    public function execute(InputInterface $input, OutputInterface $output): ?int
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }

}
